### ISSUE TITLE
Increase accuracy of containment search seeding (and reduce memory usage)

### ISSUE THREAD

**Issue by boulund** [will-rowe/groot#11]
What is the expected memory usage for groot?

I'm having issues running `groot align` on my 320GB RAM CentOS 7.5 machine, with groot `0.8.1` installed via conda. The input file is a gzipped 1.6GB FASTQ with approximately 20 M reads. I ran the following commands:

```
 groot get --out /db/groot/arg-annot 
 groot index -i /db/groot/arg-annot/arg-annot.90 --readLength 125 --containment -j 0.5 --processors 30
 gunzip -c 3920_v1_1.fastq.gz | groot align --indexDir groot-index-20181012134944/ --processors 30 > 3920_v1.groot.bam

```
The process is killed by the kernel after a while due to excessive memory usage.

**Comment by will-rowe** [comment]
Hmm, doesn’t sound good! I’ve not profiled the containment search, so maybe this isn’t a bug, I will check it out. For reference, a 2gb file runs on 4 cores with about 4gb RAM with a non containment search. Will get back to this on Monday , thanks for pointing it out!

**Comment by will-rowe** [comment]
Just profiled the containment search, something is going on there! The ensemble index query is accounting for 90% RAM usage, I will dig in to this....

**Comment by will-rowe** [comment]
The new release (1.0.0) now uses LSH ensemble for containment and I've fixed the Go routines that spiralled out of control previously. I had (embarrassingly) effectively allowed infinite Go Routines - this has now been changed to have a worker pool of "sketching" Go routines (1 per proc) and a pool of "graphing" Go routines (1 per graph). Memory use seems to be under control now
