### ISSUE TITLE
Inconsistent results with very similar read length thresholds

### ISSUE THREAD

**Issue by alexmsalmeida** [will-rowe/groot#13]
Hi Will,

I came across a bizarre case where I am getting drastically different results if I slightly change the read length thresholds (for both indexing and aligning).

I have a metagenome sequence file (publicly available in ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR503/000/SRR5032340/SRR5032340_1.fastq.gz). Using FastQC I see that the majority of reads are within the 100-101 bp window. However, the mean read length is 97 bp. So I first indexed and aligned the genome using the default 100 bp length:

```
groot index -p 4 -l 100 -i groot-db.90 -o groot-db_100bp -y groot-db_100bp.log
groot align -p 4 -l 100 -i groot-db_100bp -f SRR5032340_1.fastq.gz -o groot-db_100bp_graphs -y groot-db_100bp_align.log > groot-align.bam
groot report -i groot-align.bam -c 0.95 -y groot-db_100bp_rep.log > groot-report.tab
```

This identifies 90 different AMR genes, with counts hovering in the thousands for many of them. However, if I repeat the same procedure above but using the average read length of 97 instead of 100 for indexing and aligning (-l option), I only get 17 AMR genes, each with very low counts (100-200 reads).

I didn't expect that such a small difference in the read length option would result in such drastic differences. Do you have any idea why this would be the case and what would be the most appropriate approach to deal with this inconsistency? I am running Groot v0.7.1. I haven't yet tried the --containment option with the new version as I was having the same issues raised by another user regarding large memory requirements.

Many thanks in advance for your help.
Alex

**Comment by will-rowe** [comment]
Hi Alex,

Thanks for raising this. Do you have the log file? There is possibly something going on during the reporting here, how do the BAM files compare?

I will download the data you mention and try this out. I'm guessing I may have got some logic wrong somewhere in terms of relating graph traversals to the read lengths; resulting in many traversals not being included in reporting if the reads are longer than the window.

**Comment by will-rowe** [comment]
Thanks for the logs - they explain what's going on. The 97bp run has far fewer reads seeding (3554 vs 22315). The seeding is when a read is MinHashed and queried against graph windows using the LSH Forest index. In your case, when you drop the graph windows by 3 bases, the reads no longer meet the Jaccard similarity threshold (0.99 default in your example).

I have recreated your example (thanks for the clear description!). All you need to do is drop the Jaccard similarity threshold (-j) during indexing. I tried it with 0.95 and ~27k reads seeded against 97bp graph windows.

I'll close this now as things seem to be working correctly. Also, the latest version (0.8.2) runs this example more quickly thanks to some improvements in the hashing and db encoding etc.

Thanks again
