### ISSUE TITLE
Could the "groot" be used for the paired-end reads?

### ISSUE THREAD

**Issue by lancetxiao** [will-rowe/groot#22]
Could the "groot" be used for the paired-end reads? Tutorial does not show how to use paired-end reads data.

**Comment by will-rowe** [comment]
GROOT accepts paired-end reads but doesn't use the paired-end information. So you can just supply the data with something like this:

```
groot align -i card-90 -f reads-1.fq,reads-2.fq
```

or

```
gunzip -c *.fastq.gz | groot align -i card-90
```
