### ISSUE TITLE
encountered error: mean read length is outside the graph window size (+/- 10 bases)

### ISSUE THREAD

**Issue by lancetxiao** [will-rowe/groot#24]
Sorry again for bothering you。
command line`gunzip -c *.fq.gz | groot align -i /groot-index  -p 84`

2019/09/10 02:56:32 i am groot (version 0.8.5)
2019/09/10 02:56:32 starting the align subcommand
2019/09/10 02:56:32 checking parameters...
2019/09/10 02:56:32     input file: using STDIN
2019/09/10 02:56:32     processors: 84
2019/09/10 02:56:32     read trimming: disabled
2019/09/10 02:56:32     maximum clipped bases allowed: 5
2019/09/10 02:56:32 loading index information...
2019/09/10 02:56:32     k-mer size: 7
2019/09/10 02:56:32     signature size: 128
2019/09/10 02:56:32     Jaccard similarity theshold: 0.99
2019/09/10 02:56:32     window sized used in indexing: 100
2019/09/10 02:56:32 loading the groot graphs...
2019/09/10 02:56:32     number of variation graphs: 583
2019/09/10 02:56:32 loading the MinHash signatures...
2019/09/10 02:56:38     number of hash functions per bucket: 128
2019/09/10 02:56:38     number of buckets: 1
2019/09/10 02:56:38 initialising alignment pipeline...
2019/09/10 02:56:38     initialising the processes
2019/09/10 02:56:38     connecting data streams
2019/09/10 02:56:38     number of processes added to the alignment pipeline: 6
2019/09/10 02:56:38 now streaming reads...
2019/09/10 03:03:41     number of reads received from input: 72841016
2019/09/10 03:03:41     mean read length: 150
2019/09/10 03:03:41 encountered error: mean read length is outside the graph window size (+/- 10 bases)

**Comment by will-rowe** [comment]
Sorry for being slow to reply - I lost my notifications for this repo for some reason...

The issue here is that you indexed the graphs with a window of 100 bases, which is too small for your input reads (150 mean read length). I'd reindex using 150 as the window length.
