### ISSUE TITLE
Interpreting output plots

### ISSUE THREAD

**Issue by BioinformaticsBro** [will-rowe/groot#27]
It's expected for coverage plot to have a peak in the middle with lower coverage on the 5' & 3' ends due to seeding difficulty at the ends. But how would you interpret 'valleys' and heavily skewed peaks? My guess is that a valley is a gene that has a insertion in the middle and that a heavy skew is a duplicated region. 
![image](https://user-images.githubusercontent.com/37677948/68446064-96c12d80-0216-11ea-9011-e5ad0a76a352.png)

**Comment by will-rowe** [comment]
Hi. Thanks for getting in touch.

Yeah, that's an interesting one. Usually when I see these peaks it is because there are several genes being called from the same graph; the peaks are from the conserved region(s). Does this sound like it could be the case here based on your groot report output?

**Comment by BioinformaticsBro** [comment]
It's certainly a possibility. I'm examining human gut samples with hundreds of different species. With all the horizontal gene transfers and phylogenetically similar species, I wouldn't be surprised if there were conserved regions.

I'd like to use GROOT for my future metagenomic shotgun samples, so I'm curious to know if you'll be  working on this project in the future? It's a great program and an interesting use case for variation graphs. What else can GROOT fans expect in the future? I see the tutorial has sections that are 'coming soon'.

**Comment by will-rowe** [comment]
Thanks for your interest! I've been working on ideas for v2.0 for a while, these are being committed under a different repo; [baby groot](https://github.com/will-rowe/baby-groot). The ideas are quite different and not backwards compatible at the moment. What I hope to do is merge in the ideas from baby-groot once it is stable. This would mean support for variable read lengths, faster alignment, and a web front end. I should caveat all this by saying I've started a new job and GROOT is now a side project for me! You've also given me a kick to improve the documentation...

**Comment by BioinformaticsBro** [comment]
Cool, looking forward to it! Antimicrobial resistance is and will be a hot topic so I'm sure there'll be a big demand for ARG detection tools. Good luck!
