### ISSUE TITLE
Containment not option not present in 0.8.5 on OSX

### ISSUE THREAD

**Issue by dcdanko** [will-rowe/groot#28]
Looks like the containment option is not present on my version of groot. (0.8.5 installed via bioconda to OSX)

```
(base) dcdanko@mac196156:~/Dev/cap2
$ vendor/conda/CAP_v2/bin/groot version
0.8.5
(base) dcdanko@mac196156:~/Dev/cap2
$ vendor/conda/CAP_v2/bin/groot index -i tests/data/groot_amrs -o bar -l 250 --containment -j 0.5
Error: unknown flag: --containment
Usage:
  groot index [flags]

Flags:
  -h, --help             help for index
  -j, --jsThresh float   minimum Jaccard similarity for a seed to be recorded (default 0.99)
  -k, --kmerSize int     size of k-mer (default 7)
  -i, --msaDir string    directory containing the clustered references (MSA files) - required
  -o, --outDir string    directory to save index files to (default "./groot-index-20191112133350")
  -l, --readLength int   length of query reads (which will be aligned during the align subcommand) (default 100)
  -s, --sigSize int      size of MinHash signature (default 128)

Global Flags:
  -y, --logFile string   filename for log file (default "./groot.log")
  -p, --processors int   number of processors to use (default 1)
      --profiling        create the files needed to profile GROOT using the go tool pprof
```

Any obvious fix?

**Comment by will-rowe** [comment]
Hey @dcdanko. Thanks for raising this. You are right, it was removed in the latest version after finding it was causing some really high memory use (see [this issue](https://github.com/will-rowe/groot/issues/11)). As GROOT is meant to be fast, I decided to just remove it until I got it working efficiently. In the mean time, see [baby groot](https://github.com/will-rowe/baby-groot) for a containment-enabled GROOT. It's not released yet but close to ready - I plan on then merging the features into GROOT.

**Comment by dcdanko** [comment]
What version was it removed? For now I'm just interested in building out and testing a pipeline so performance doesn't matter to me yet.

**Comment by will-rowe** [comment]
Sorry for the delay in this - only just finding time to get back to some GROOT dev.

I've added containment back for the latest release (1.0.0) which should hopefully be in conda soon. Containment is now the default (only option) - I've had to change some of the CLI though - sorry!
