### ISSUE TITLE
Building custom database, memory overconsumption.

### ISSUE THREAD

**Issue by Sebastien-Raguideau** [will-rowe/groot#29]
Hello,
I'm trying to index a custom database of 35 .msa weighting about 71mo. 
My issue is that for some reason it takes an incredible amount of memory to build. I'm talking 2T of ram. Well, It took 2T before beeing killed by the system, so actually I never managed to build the db yet. At first I thought it may be related to number of cpu, I was running with 100 or so. I am running the same command with only 1 cpu and at the moment we are at 360G of ram taken.
The memory overcomsumption happens at the following step:
windowing graphs and generating MinHash signatures.
Do you have any clue?
Best,
Seb

**Comment by will-rowe** [comment]
Hi Seb,

Thanks for getting in touch. This sounds like a bug. What's the max sequence length in each of the MSAs? And how diverse are they/what clustering identity did you use?

The indexing in GROOT is a bit inefficient - I have just improved this in baby groot and will incorporate these changes here in a new release. That being said, you shouldn't be seeing 360GB when indexing 35 small graphs with 1 core....

Please also let me know what GROOT version you are using.

**Comment by Sebastien-Raguideau** [comment]
Hi Will,

Thanks for the quick answer!

So, there's maybe an issue with the way I proceed. I'm working on Cogs, they are orthologous but not always super similar. I used an existing msa alignment build with mafft on its accurate setting, without any clustering. 

I had a look right now on one of the COG, If I do a vsearch clustering at 0.90, it clusters 688 sequences in 683 clusters. At 0.5, it's still something like 19 clusters. What do you advise as the best way to proceed? Should I split each of these COG in multiple .msa after some lax clustergin?
 
The longest of these .msa is 13387 while the smallest is at 627.

I'm using conda for install, GROOT version there is  0.8.5.

**Comment by will-rowe** [comment]
Yeah - GROOT is more designed to separate variants of a single gene. I've only really tested on gene clusters that share >80% identity. That is also quite a long sequence you have there; I've only tried variation graphs where the genes are much shorter. I think the both of these things taken together means that GROOT is struggling here.

It should be better than this but I'm not sure I can make significant improvements here. Maybe something like vg might be a better tool for the job?

**Comment by Sebastien-Raguideau** [comment]
Ok, that makes sense. 
I'll have a look at vg then. 
Thanks!
