### ISSUE TITLE
Out-of-memory failure v0.8.6

### ISSUE THREAD

**Issue by EmilyCrossette** [will-rowe/groot#31]
With version 0.8.6, my align processes is failing due to memory. The same command with the same fastq file size worked before with v0.8.5 and the resfam90 index.  I am now using an index of CARD and running with 0.8.6 with 8 threads and as much memory as I am allowed to allocate on my computing cluster.

**Comment by will-rowe** [comment]
Thanks for raising this issue - sounds odd. Can I just clarify, the only thing that changed is the software version? Or did you also change the index from resfam to CARD?

Either way, it sounds like there is a bug that is causing GROOT to use too much memory. I'll investigate

**Comment by EmilyCrossette** [comment]
Thanks for clarifying, Will! 

In the process that failed due to the memory issues, I indexed CARD and used this in my analysis using version 0.8.6. The process had previously worked with the 0.8.5 but I used the resfam index then since I couldn't index card with version 0.8.5. (so in that case only my read files are the same)

Interestingly, the resfam index directory (~700M) is 5x bigger than the CARD index directory (140M). I am not sure if this at all relevant but it caught my attention.

**Comment by will-rowe** [comment]
Heya @EmilyCrossette 

Sorry for the looong delay here - I've finally got around to improving GROOT and fixing this bug from the last release. There's now a new release in conda (1.0.2). If you're still using GROOT, please let me know that this release fixes things for you.
