### ISSUE TITLE
Trimming and read length?

### ISSUE THREAD

**Issue by Thomieh73** [will-rowe/groot#32]
Hi, 
I contact you because I am having some trouble running Groot.

My data:
I have a collection of metagenomic samples and I have qc'ed my paired-end shotgun sequences using  the [Sunbeam pipeline](https://sunbeam.readthedocs.io/en/latest/). For the AMR detection, I have created a Groot database, based on the Megares database, which detects quite a bit of AMR genes in my samples.

My problem:
Since I have access to the SAGA compute cluster, I use a slurm script to process the samples with Groot and my megares databases, and there i have something funny happening...
Most of my samples are analyzed, and I get the output, but for four samples I have jobs failing, and it seems that it is due to the average read length of those samples. Since I have paired end data, I run each read set with align and then I combined the bam files to generate the final output file. (reason was that Groot used a lot of memory, when running the R1 and R2 files together)

The command that I used is the following

``` 
groot align -i megares_db \
     -f fasta_file_R1.fastq \
     -y file_R1.align.log \
      -l 150 \
     - p 10
     -o file_R1.groot-graphs > file_R1.bam 
```

``` 
groot align -i megares_db \
     -f fasta_file_R2.fastq \
     -y file_R2.align.log \
      -l 150 \
     - p 10
     -o file_R2.groot-graphs > file_R2.bam 
``` 

For some of my datasets, they crash when running the second command. When I check those datasets, they had an average read length below 140 for the reverse reads but not the forward reads. My database was indexed using a length of 150.

So my question is, why do I want to set the read length for the align step, or should I only do that in conjunction with the --trim option?  Long reads are better for classification, than short ones, I would think.

and what happens in the trimming? Will that only remove low quality bases, or does it also throw away reads that are to short?

**Comment by Thomieh73** [comment]
Okay, I now understand the issue I am having.

The datasets that get killed have an read length that is outside the graph window size. To build the database I used a window size of 150. 

Groot align then wants files that have an average read length of 150 +/- 10.

So if I build my database with a length of say 141, then all datasets that have a mean read length between 131 and 151 should be accepted, right?

**Comment by Thomieh73** [comment]
Just an update, I have build my database now with a length of 141, and tried it out with dataset that had an average read length of 137. That did work now, and I have now started processing all my samples.
I close this issue.

**Comment by will-rowe** [comment]
Hey @Thomieh73 - really sorry for missing this issue. I didn't get an alert for some reason. Glad it's working for you now and please let me know if you need further assistance
