### ISSUE TITLE
out of memory error ( > 256 GB)

### ISSUE THREAD

**Issue by rizkg** [will-rowe/groot#33]
This may be linked to issue #31 

I ran groot version 0.8.6 using the groot-db and had a out of memory error during read alignment. This is with a pair of fastq.gz files of 2x 1 GB.
My computer has 256 GB ram.

This is the commands I used for index creation and alignment :

     groot get -d groot-db -i 90 -o .

     groot index -i  groot-db.90/ -o groot-index-groot-db -p 8 -l 100

     groot align -i groot-index-groot-db -f S1_R1.fastq.gz,S1_R2.fastq.gz -p 20  > S1_res_groot.bam

Wich results in  :

```

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb36987, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xfc1c000000, 0x4000000, 0x12bfff8)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x12a5ec0, 0x2000, 0x3f, 0xb20)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x12a5ec0, 0x1, 0xf9ffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x12a5ec0, 0x1, 0x12c0008, 0xe124e0)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x12a5ec0, 0x1, 0xfae75c0008, 0x0)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.systemstack(0xc0000d0480)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

```

**Comment by rizkg** [comment]
Hello again,  groot v 0.8.5 with the same command, fastq files and database worked correctly.
If you need additional information to find the issue I will be happy to assist.

And by the way, thanks for this great software, that is exactly what I was looking for.

**Comment by will-rowe** [comment]
Thank you for the thorough error report @rizkg - I'm not sure what I've done do mess this up and not catch it! I am trying to find some time to get back to this and fix that version in the next few days. Definitely use v0.8.5 for now!

**Comment by will-rowe** [comment]
Heya @rizkg. I finally got around to fixing 0.8.6 - and added in a bunch more improvements. You should find v1.0.2 in conda now. Please let me know how you get on.

**Comment by rizkg** [comment]
great, thank you very much !
