### ISSUE TITLE
Groot containment searching

### ISSUE THREAD

**Issue by LeonardosMageiros** [will-rowe/groot#34]
Hi!

I have a metagenomic dataset that after QC contains reads of variable length. 
Can you please explain to me how the containment searching in the index command works? 
If I understand correctly that is the parameter I should use for my index command. 

How can I determine what number I should give to that argument?

Thank you in advance.
Leonardos

**Comment by will-rowe** [comment]
Heya.

Thanks for getting in touch. I'm sorry not to have responded sooner.

I removed the containment feature in the last release as it was resulting in really high memory usage and wasn't really fit for purpose. I didn't realise I hadn't removed it from the README! My bad.

I'm trying to find the time to merge over the containment work I've done in baby-groot, hopefully within the next week or so. For now, please use version 0.8.5 of GROOT (which doesn't have containment)

**Comment by LeonardosMageiros** [comment]
Hi, 

Thx for the response. 
Can you let me know please how I can install version 0.8.5? 
Can i do it with conda? 

Thx

**Comment by will-rowe** [comment]
Hi @LeonardosMageiros - there is now a new version of GROOT which fixes these issues and adds a bunch of improvements. This should be available in conda (v1.0.2) - so just install/upgrade:

```
conda install -c bioconda groot=1.0.2
```
