### ISSUE TITLE
protein database maybe More conservative than DNA

### ISSUE THREAD

**Issue by feihongloveworld** [will-rowe/groot#43]
hi sir：
       Groot is Very interesting method with variation graph to detect AMR subtype,
       Considering the conservation of protein，protein database maybe better than  DNA。
      Another problem， how can i build myself database index in fasta file？
thanks

**Comment by will-rowe** [comment]
Hi there.

Thanks for getting in touch. Yes, protein databases are a nice idea and I'd like to implement them at some stage.

In terms of custom databases from fasta, this is documented [here](https://groot-documentation.readthedocs.io/en/latest/groot-databases.html). You need to cluster the fasta using vsearch or similar.

Please reopen this issue if you need anything else.

Cheers,

Will
