### ISSUE TITLE
how to select reasonable ARG result ? 

### ISSUE THREAD

**Issue by feihongloveworld** [will-rowe/groot#44]
hi sir：
       i run groot wiht card database version 3.0.8  index -w 75; and reprot -c 0.95 .
     a metagenomic sample result show as below:
'''
GeneName      ReadsCount  GeneLength  CIGAR                         DL   ML    ML_Rate
Name:ADC-1    151         1152        2D718M23D278M15D109M7D        47   1105  0.95920
Name:ADC-25   153         1152        2D730M11D278M2D122M7D         22   1130  0.98090
Name:ADC-30   163         1152        2D730M11D402M7D               20   1132  0.98264
Name:ADC-31   135         1152        2D573M13D144M11D278M2D122M7D  35   1117  0.96962
Name:ADC-56   155         1152        2D510M6D214M11D402M7D         26   1126  0.97743
Name:ADC-61   145         1152        2D573M13D144M11D402M7D        33   1119  0.97135
Name:ADC-67   158         1152        2D730M11D383M26D              39   1113  0.96615
Name:ADC-73   169         1152        2D1143M7D                     9    1143  0.99219
Name:ADC-75   156         1152        2D730M11D92M15D295M7D         35   1117  0.96962
Name:ADC-82   162         1152        2D718M23D402M7D               32   1120  0.97222
Name:OXA-23   279         822         13D806M3D                     16   806   0.98054
Name:OXA-27   207         822         13D142M9D117M2D455M3D78M3D    30   792   0.96350
Name:OXA-49   242         825         13D429M3D377M3D               19   806   0.97697
Name:OXA-66   109         825         7D810M8D                      15   810   0.98182
Name:OXA-73   253         822         13D725M3D78M3D                19   803   0.97689
Name:OXA-76   105         825         7D799M19D                     26   799   0.96848
Name:OXA-79   96          825         7D656M11D143M8D               26   799   0.96848
Name:OXA-80   101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-83   101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-84   94          825         7D366M21D109M5D309M8D         41   784   0.95030
Name:OXA-109  101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-127  100         825         7D483M18D309M8D               33   792   0.96000
Name:OXA-146  279         825         13D809M3D                     16   809   0.98061
Name:OXA-165  267         822         13D806M3D                     16   806   0.98054
Name:OXA-166  265         822         13D806M3D                     16   806   0.98054
Name:OXA-168  268         822         13D678M1D127M3D               17   805   0.97932
Name:OXA-169  257         822         13D117M13D676M3D              29   793   0.96472
Name:OXA-170  257         822         13D605M6D195M3D               22   800   0.97324
Name:OXA-177  90          825         7D483M18D88M1D220M8D          34   791   0.95879
Name:OXA-202  101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-206  101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-225  268         822         13D657M5D144M3D               21   801   0.97445
Name:OXA-234  96          825         7D656M11D143M8D               26   799   0.96848
Name:OXA-239  242         822         13D309M4D331M18D144M3D        38   784   0.95377
Name:OXA-254  101         825         7D366M21D423M8D               36   789   0.95636
Name:OXA-260  108         825         21D796M8D                     29   796   0.96485
Name:OXA-336  99          825         7D496M17D297M8D               32   793   0.96121
Name:OXA-398  268         822         13D657M5D144M3D               21   801   0.97445
Name:OXA-422  257         822         38D781M3D                     41   781   0.95012
Name:OXA-435  268         822         13D678M1D127M3D               17   805   0.97932
Name:OXA-440  267         822         13D655M7D144M3D               23   799   0.97202
Name:OXA-482  241         822         13D102M6D698M3D               22   800   0.97324
'''
there are too many ADC gene and OXA gene subtype.
so many subtype of one gene in one clinic sample seem   unreasonable；so how should i to select reasonable result from groot raw result？
thanks

**Comment by will-rowe** [comment]
That's a good question. Firstly, I would try increasing the report threshold from 95% to nearer 100%, that should remove some of the subtypes you are seeing. Particularly where you have mismatches in the middle of the alignments.

As you can see from the CIGAR style strings in that report, you have a lot of leading and terminal Ds. This is a partly due to one of GROOT's limitations in that coverage is always lower at the ends of the graphs (as any reads which span the gene and it's flanking regions tend to be ignored) . This isn't a problem usually in high coverage samples but when coverage is low, I find that if I trim a bit more aggressively, terminal coverage tends to improve.

GROOT is designed to get you a resistome profile quickly, I'd recommend taking this profile and then using a readmapper to confirm.

Hope this helps. Let me know if you have any more questions.
