### ISSUE TITLE
Error on installation from source

### ISSUE THREAD

**Issue by noellenoyes** [will-rowe/groot#45]
Hello, I am trying to install groot from source onto a Linux server. I receive the following error message when attempting to both test (go test -v ./...) and compile (go build ./) the install: "segment.GetKmerCount undefined (type *gfa.segment has no field or method GetKmerCount)".   I do have go installed and working on the server.

**Comment by will-rowe** [comment]
Thanks for getting in touch.

I'm not able to reproduce this - tests are working for me using the master branch and running the commands as in the readme. I'm using Go 1.14

Are you using the master branch or source from a release? Also, what version of Go are you using?
