### ISSUE TITLE
Abundance table

### ISSUE THREAD

**Issue by mhmism** [will-rowe/groot#47]
Hello,

Thank you for this great pipeline!

Is there a way to merge all groot reports into a single abundance table in a similar way to ASVs/OTUs tables?

Thanks a lot in advance!

**Comment by will-rowe** [comment]
Hi there. Thanks for your interest in GROOT!

GROOT doesn't have a way to do that built in, but maybe you could do some bash scripting to combine the reports?

If you had an example of what you are after, maybe we could look at adding something to GROOT?

**Comment by mhmism** [comment]
Thanks will for your kind response.

I will try out some scripting and share once done. 

Would it be good to report the read count in this table, or should we consider normalization (e.g. relative abundance, others) before downstream analyses (e.g. differential abundance, diversity, etc.)? 

I was thinking something like (read counts are reported), let me know your opinion?

ARG   Sample1   Sample2    Sample3
TetQ       150            0                0
mexY      100            0                0
MexZ         0             0              200
mfd            0           19               50
