### ISSUE TITLE
Card db

### ISSUE THREAD

**Issue by kayobianco** [will-rowe/groot#51]
Hi,

I'm trying to get the CARD database, but I have the following output:

(groot) kayobianco@arqueas:~$ groot get -d card
downloading the pre-clustered card database...
unpacking...
could not unpack the tarball
md5sum for downloaded tarball did not match record

Can you help me?

**Comment by will-rowe** [comment]
Hi. Can you open the downloaded file? Sounds like a corrupted download; this error is telling you that the downloaded file isn't what is expected.
