### ISSUE TITLE
GROOT and long reads

### ISSUE THREAD

**Issue by taylorjohnsonm** [will-rowe/groot#52]
Hi, I'm currently testing GROOT on Nanopore data and am getting this error --> panic: k size is greater than sequence length (31 vs 1). Please let me know if GROOT is compatible with Nanopore data and if so, how to fix this error. Thanks!

**Comment by will-rowe** [comment]
Hi! This panic means that you have one or more read in your fastq that is shorter than your k-mer size. The fact that it is 1 makes me think that there is a problem with the input; I'd run it through QC. I've never tried GROOT with nanopore data but I don't see why not - it's probably not the best tool for the job though. Thanks for your interest in GROOT!
