### ISSUE TITLE
panic: k size is greater than sequence length (31 vs 25)

### ISSUE THREAD

**Issue by arpit20328** [will-rowe/groot#54]
(base) arpit@jarvis:~/groot$ ls *.fastq | parallel --gnu "groot align -i groot-index -f {} -p 8 -g {/.}-groot-graphs > {/.}.bam"
panic: k size is greater than sequence length (31 vs 25)

goroutine 649 [running]:
github.com/will-rowe/groot/src/pipeline.(*theBoss).mapReads.func1(0x0?)
        /opt/conda/conda-bld/groot_1713954573131/work/src/pipeline/boss.go:165 +0x4fa
created by github.com/will-rowe/groot/src/pipeline.(*theBoss).mapReads in goroutine 12
        /opt/conda/conda-bld/groot_1713954573131/work/src/pipeline/boss.go:136 +0x295

Please resolve the issue . @will-rowe

**Comment by will-rowe** [comment]
Hi. This isn't an issue with GROOT - the error is telling you you have one or more sequences in your input that are shorter than your chosen k-mer length. Try QC-ing and filtering your input reads and then assessing what size k-mer is suitable for your input.
